temail.gateway:
  port: 8099
  namesrvAddr: 192.168.15.37:9876
  verifyUrl: http://192.168.15.123:8081/verify
  dispatchUrl: http://192.168.15.123:8081/dispatch
  updateSocketStatusUrl: http://192.168.15.228:9100/updateStatus
  allow-lose-count: 10
  readIdleTimeSeconds: 180
  consumerGroup: cdtp-server-consumer
  mqTopic: temail.gateway